package wsrsrc

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// forgeSpecPlaybook is the canonical lead-forge-spec playbook. The
// agents-plugin-wsflow copy is a generated byte-identical mirror
// (TestWsflowRsrcMirrorUpToDate), so guarding the canonical file guards both.
func forgeSpecPlaybook() string {
	return filepath.Join(shippedRsrcRoot(), "lead-forge-spec", "lead-forge-spec.md")
}

// markdownSection returns the lines under an H2 heading, stopping at the next
// H2. Fenced blocks are tracked because the wrap-up's report template is a
// fenced block whose first line is itself an H2 ("## Forge Spec - Complete");
// a naive scan would cut the section there.
func markdownSection(text, heading string) (string, bool) {
	var body []string
	inSection, inFence := false, false
	for _, line := range strings.Split(text, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "```") {
			inFence = !inFence
		}
		if !inFence && strings.HasPrefix(line, "## ") {
			if line == heading {
				inSection = true
			} else if inSection {
				break
			}
		}
		if inSection {
			body = append(body, line)
		}
	}
	if !inSection {
		return "", false
	}
	return strings.Join(body, "\n"), true
}

// TestForgeSpecWrapUpReportsFromTheAmbiguityRecord pins one safety-critical
// contract: lead-forge-spec's wrap-up summary sources its ambiguity list from
// the in-run record produced by the classification pass, not from the
// <!-- AMBIGUOUS --> markers embedded in written spec entries.
//
// Why this one playbook contract earns a content guard while the rest of rsrc/
// is guarded for consistency only: items classified planned or internal-only
// are never written to the spec, so they carry no marker. A wrap-up that
// collects markers silently omits exactly the autonomous judgment calls the
// user was promised a chance to review, and the omission is invisible at
// runtime - the procedure completes and the report is emitted, just short some
// rows. That hole has now been introduced twice by fixes, once by scoping the
// collection to step 5 and once by the repair of that scoping.
//
// Asserted on substance, the way TestWorkflowGuidesKeepImplementationGapException
// is: the wrap-up must name a record as its source and must name both
// spec-excluded classifications, in any wording. It deliberately says nothing
// about sentence shape, and it does not forbid mentioning the markers - the
// current text names them as the reconstruction path for a resumed run.
func TestForgeSpecWrapUpReportsFromTheAmbiguityRecord(t *testing.T) {
	path := forgeSpecPlaybook()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}

	const wrapUpHeading = "## On: wrap-up"
	body, ok := markdownSection(string(raw), wrapUpHeading)
	if !ok {
		t.Fatalf("%s: no %q handler; the wrap-up summary contract has no home", path, wrapUpHeading)
	}
	lowered := strings.ToLower(body)

	var missing []string
	if !strings.Contains(lowered, "record") {
		missing = append(missing, `no record named as the ambiguity list's source (so it can only be `+
			`reading the inline markers, which planned and internal-only items never carry)`)
	}
	for _, classification := range []string{"planned", "internal-only"} {
		if !strings.Contains(lowered, classification) {
			missing = append(missing, "no mention of "+classification+
				" items, a spec-excluded classification the record exists to carry into the summary")
		}
	}
	if len(missing) > 0 {
		t.Errorf("%s: %s\n%s: %q", path, strings.Join(missing, "; "), wrapUpHeading, body)
	}
}
